import { Unit } from "./types";

// Default roster used to seed the database the first time it is empty.
// Names transcribed from the reference 7k-combo roster. Portraits are not
// included — upload them per-character from the "จัดการตัวละคร" page
// (/admin/characters); until then the generated gradient is used.

let hueSeed = 0;
const nextHue = () => (hueSeed = (hueSeed + 47) % 360);

function mk(
  name: string,
  category: Unit["category"],
  stars = 5,
  kind: Unit["kind"] = "character"
): Unit {
  return {
    id: `${category}-${name}`.toLowerCase().replace(/\s+/g, "-"),
    name,
    category,
    kind,
    stars,
    hue: nextHue(),
    image: null,
  };
}

const c = (name: string, category: Unit["category"]) => mk(name, category);
const pet = (name: string, category: Unit["category"]) => mk(name, category, 5, "pet");

export const DEFAULT_UNITS: Unit[] = [
  // ── O7K ──────────────────────────────────────────────────────────────
  c("เกลลิดัส", "o7k"),
  c("จูริ", "o7k"),
  c("ไพร์", "o7k"),
  c("มิเลีย", "o7k"),
  c("โรซี่", "o7k"),

  // ── Awake ────────────────────────────────────────────────────────────
  c("เคลมิส", "awake"),
  c("เดลโลนส์", "awake"),
  c("สกัลด์", "awake"),
  c("ซิลเวสตา", "awake"),

  // ── ทองบน (gold-top) ─────────────────────────────────────────────────
  c("เคลมิส", "gold-top"),
  c("สกัลด์", "gold-top"),
  c("คาร์ล เฮรอน", "gold-top"),
  c("โอมัก", "gold-top"),
  c("มิสต์", "gold-top"),
  c("นาจา", "gold-top"),
  c("แรนด์กริด", "gold-top"),
  c("ซองจินอู", "gold-top"),
  c("เรกินเลฟ", "gold-top"),
  c("แร็ดกริด", "gold-top"),
  c("ลิโป้", "gold-top"),
  c("พาลานอส", "gold-top"),
  c("บรันซ์ & บรันเซล", "gold-top"),
  c("ชุนหงอคง", "gold-top"),
  c("เฟรย่า", "gold-top"),
  c("ธรูด", "gold-top"),
  c("ไรอัน", "gold-top"),
  c("เอลิเซีย", "gold-top"),
  c("คิริเอล", "gold-top"),
  c("ไคล์", "gold-top"),
  c("อากีลา", "gold-top"),
  c("คางุระ", "gold-top"),
  c("พยัคฆ์เมฆา", "gold-top"),
  c("ออร์ลี่", "gold-top"),
  c("บิสกิต", "gold-top"),
  c("เพลตัน", "gold-top"),
  c("โคลท์", "gold-top"),
  c("ริน", "gold-top"),
  c("คาร์ม่า", "gold-top"),
  c("เมลคีร์", "gold-top"),
  c("ยอนฮี", "gold-top"),
  c("แทโอ", "gold-top"),
  c("วาเนสซา", "gold-top"),
  c("สไปค์", "gold-top"),
  c("เจฟ", "gold-top"),
  c("ราเชล", "gold-top"),
  c("ไอลีน", "gold-top"),
  c("เดลโลนส์", "gold-top"),
  c("คริส", "gold-top"),
  c("ลูดี้", "gold-top"),
  c("ซิลเวสตา", "gold-top"),
  c("เอช", "gold-top"),
  c("วิคตอเรีย", "gold-top"),

  // ── ทองล่าง (gold-bottom) ────────────────────────────────────────────
  c("ชาแฮอิน", "gold-bottom"),
  c("กวนอู", "gold-bottom"),
  c("ไป่หลง", "gold-bottom"),
  c("เสียวเฉียว", "gold-bottom"),
  c("เตียวเสี้ยน", "gold-bottom"),
  c("ไป่เฉียว", "gold-bottom"),
  c("เอมิเลีย", "gold-bottom"),
  c("มิโฮะ", "gold-bottom"),
  c("เดซี่", "gold-bottom"),
  c("ทากะ", "gold-bottom"),
  c("ปาสคาล", "gold-bottom"),
  c("อารากอน", "gold-bottom"),
  c("อลิช", "gold-bottom"),
  c("บาลิสต้า", "gold-bottom"),
  c("ชานชะเลอร์", "gold-bottom"),
  c("ลุค", "gold-bottom"),
  c("ซีค", "gold-bottom"),
  c("เอสปาด้า", "gold-bottom"),
  c("เนีย", "gold-bottom"),
  c("เบลลีก้า", "gold-bottom"),
  c("รีน่า", "gold-bottom"),
  c("พีดัม", "gold-bottom"),
  c("ยูชิน", "gold-bottom"),
  c("น็อกซ์", "gold-bottom"),
  c("ลูลี่", "gold-bottom"),

  // ── อีปิค (epic) ─────────────────────────────────────────────────────
  c("คารอน", "epic"),
  c("คาริน", "epic"),
  c("แคทตี้", "epic"),
  c("โคลอี้", "epic"),
  c("จิน", "epic"),
  c("จูพี", "epic"),
  c("จูล่ง", "epic"),
  c("เจน", "epic"),
  c("โจ๊กเกอร์", "epic"),
  c("ซาร่า", "epic"),
  c("ซิลเวีย", "epic"),
  c("เซร่า", "epic"),
  c("โซอี", "epic"),
  c("คลีโอ", "epic"),
  c("โนโฮ", "epic"),
  c("เบน", "epic"),
  c("แบล็คโรส", "epic"),
  c("เฟิงเยี่ยน", "epic"),
  c("เมย์", "epic"),
  c("ยูจินโฮ", "epic"),
  c("ยูอิ", "epic"),
  c("เรย์", "epic"),
  c("แรคคูน", "epic"),
  c("ลาเนีย", "epic"),
  c("ลี", "epic"),
  c("ลีโอ", "epic"),
  c("ลูซี่", "epic"),
  c("สนิปเปอร์", "epic"),
  c("เสี่ยว", "epic"),
  c("หลิงหลิง", "epic"),
  c("อสุรา", "epic"),
  c("อีจูฉี", "epic"),
  c("อีวาน", "epic"),
  c("เอเรียล", "epic"),
  c("เฮฟเว่นเนีย", "epic"),
  c("เฮเลเนีย", "epic"),
  c("ยูริ", "epic"),
  c("โฮกิน", "epic"),

  // ── สัตว์เลี้ยง — เลเจนด์ (legend pets) ───────────────────────────────
  pet("อีรีน", "legend"),
  pet("ยอนจี", "legend"),
  pet("ยู", "legend"),
  pet("ลู", "legend"),
  pet("คารัม", "legend"),
  pet("ไพค์", "legend"),
  pet("เมลแปร์โรว์", "legend"),
  pet("วินดี้", "legend"),
  pet("จีฟ", "legend"),
  pet("เจโอ", "legend"),
  pet("โยรัง", "legend"),
  pet("รีเซล", "legend"),
  pet("ครี", "legend"),
  pet("เดลโล่", "legend"),
  pet("ดอจ", "legend"),
  pet("มิค", "legend"),
  pet("เอริ", "legend"),

  // ── สัตว์เลี้ยง — อีปิค (epic pets) ───────────────────────────────────
  pet("โน้ต", "epic"),
  pet("เชรี", "epic"),
  pet("โครอา", "epic"),
  pet("พารากอน", "epic"),
  pet("เฮเลพิน", "epic"),
  pet("เฟิงน้อย", "epic"),
  pet("นีน่า", "epic"),
  pet("นิกิ", "epic"),
  pet("มิวมิว", "epic"),
  pet("มีมิค", "epic"),
  pet("ทู", "epic"),
];
